spring:
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
  data:
    mongodb:
      authenticationDatabase: admin
      username: root
      password: root
      host: localhost
      port: 27017
      database: github-crawler
server:
  port: 8081
